query {
  categories {
    id
    name
    href
    slug
    children {
      id
      name
      href
      slug
      children {
        id
        name
        href
        slug
      }
    }
  }
}
